### ISSUE TITLE
如何打印所有请求相关数据呢

### ISSUE THREAD

**Issue by gmfbilu** [Ayvytr/OKHttpLogInterceptor#1]
如何打印所有请求相关数据呢

**Comment by Ayvytr** [comment]
LoggingInterceptor interceptor = new LoggingInterceptor(LoggingLevel.ALL);

LoggingLevel.ALL会打印最详细请求数据

**Comment by Ayvytr** [comment]
[LoggingLevel.java](https://github.com/Ayvytr/OKHttpLogInterceptor/blob/master/okhttploginterceptor/src/main/java/com/ayvytr/okhttploginterceptor/LoggingLevel.java)
