### ISSUE TITLE
OkHttp-Request和OkHttp-Response会混在一起打印，建议打印方法加个锁

### ISSUE THREAD

**Issue by Khaos116** [Ayvytr/OKHttpLogInterceptor#2]
![image](https://user-images.githubusercontent.com/11989916/100335163-40808180-3007-11eb-805c-328d962b32c8.png)

**Comment by Ayvytr** [comment]
目前已在LoggingInterceptor类使用Executors.newSingleThreadExecutor()进行了Request和Response分开处理，但是效果不理想，如果你有更好的方案请分享一下
```kotlin
private val requestExecutor = Executors.newSingleThreadExecutor()
private val responseExecutor = Executors.newSingleThreadExecutor()

```

**Comment by Khaos116** [comment]
就是在方法上增加synchronized，同步锁住
不过可能需要把你这两个方法放到一个方法中，通过布尔值判断了

**Comment by Khaos116** [comment]
大概就是这样
![image](https://user-images.githubusercontent.com/11989916/101590008-29d12600-3a1c-11eb-92a1-57334ce37a48.png)

**Comment by Khaos116** [comment]
当然有可能添加这个又会导致之前版本你说的请求1秒钟，打印5秒钟的问题了，这个要看怎么处理了

**Comment by Ayvytr** [comment]
解决了，发了3.0.4。如果有其他问题再反馈哈

**Comment by Khaos116** [comment]
感谢大佬
