### ISSUE TITLE
关于Gson包找不到的问题

### ISSUE THREAD

**Issue by v200123** [Ayvytr/OKHttpLogInterceptor#3]
目前我项目用的Moshi，在加入你的Log打印库后无法找到Gson的包，所以可以选择将其直接依赖进来

**Comment by Ayvytr** [comment]
目前拦截器依赖了gson如下：
```
    compileOnly "com.google.code.gson:gson:2.8.5"

```
并且新建工程重新依赖进行编译可以通过。不知道你说的问题具体是怎样的，是直接编译不通过还是使用gson的时候说找不到？

**Comment by v200123** [comment]
报了cannot find class

`Didn't find class "com.google.gson.JsonParser" on path: DexPathList[[zip file "/data/app/~~Cof7PRKkGbz7jatSDXIL3g==/com.last_coffee.myutillib-slDcJdH6UchivFbbdEcgvQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~Cof7PRKkGbz7jatSDXIL3g==/com.last_coffee.myutillib-slDcJdH6UchivFbbdEcgvQ==/lib/arm64, /data/app/~~Cof7PRKkGbz7jatSDXIL3g==/com.last_coffee.myutillib-slDcJdH6UchivFbbdEcgvQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /vendor/lib64, /odm/lib64]]

com.ayvytr.okhttploginterceptor.ExtKt.jsonFormat(Ext.kt:164)`

**Comment by v200123** [comment]
我看了看compileOnly的作用，这个只参与编译，但是不加入打包流程。这只是个建议，毕竟总有人没依赖Gson这个库，可以在markdown中进行说明

**Comment by Ayvytr** [comment]
rebuild没报这个问题，报错是编译的时候？implementation导入的？

**Comment by v200123** [comment]
嘿嘿嘿，你应该是在其他位置导入过Gson的包，我自己导入后也是正常的。我只是想提示compileOnly是只参与编译但不参与打包。你可以做一个提示

**Comment by Ayvytr** [comment]
你有时间方便的话，制作个报这个错的demo发我看一下
